# Generated by Django 4.1.3 on 2022-11-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
