# Generated by Django 4.1.2 on 2022-10-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orphans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('dateofbirth', models.DateTimeField(auto_now_add=True)),
                ('placeofbirth', models.CharField(max_length=255)),
                ('orphan', models.CharField(max_length=255)),
                ('dateofreceipt', models.DateTimeField(auto_now_add=True)),
                ('dateofdeduction', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
