# Generated by Django 4.1.2 on 2022-10-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphans',
            name='dateofbirth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orphans',
            name='dateofdeduction',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orphans',
            name='dateofreceipt',
            field=models.DateTimeField(),
        ),
    ]
