# Generated by Django 4.1.2 on 2022-10-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_orphans_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphans',
            name='dateofbirth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orphans',
            name='dateofdeduction',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orphans',
            name='dateofreceipt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
