# Generated by Django 4.1.3 on 2022-11-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_groups_relatives_alter_orphans_deduction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orphans',
            old_name='deduction',
            new_name='expelled',
        ),
        migrations.AddField(
            model_name='orphans',
            name='diagnostics',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orphans',
            name='featuresdiagnostics',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orphans',
            name='riskgroup',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
