# Generated by Django 4.1.3 on 2022-11-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orphans_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphans',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
