# Generated by Django 4.1.3 on 2022-11-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_orphans_number_alter_orphans_diagnostics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphans',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
