# Generated by Django 4.1.3 on 2022-11-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_orphans_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relatives',
        ),
    ]
